name: Sally Kadylo
favicon: null
layout_spectrum: 0.454230226110667
typography_spectrum: 0.82533
title: Teaching Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
